version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    #env_file: 
    #  - ./api/.env
    environment: 
      - MONGO_APP_USER
      - MONGO_APP_PWD
      - NODE_ENV=production
    restart: unless-stopped
    depends_on: 
      - db
  db:
    image: mongo
    volumes: 
      - type: volume
        source: dbprod
        target: /data/db
    #env_file: 
    #  - ./db/.env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on: 
      - api
      - client
    restart: unless-stopped
volumes: 
  dbprod:
    external: true